workflows:
  ios-workflow:
    name: iOS Release Build (Unsigned)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Create .env file
        script: |
          cp .env.production .env
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build iOS with xcodebuild (no signing)
        script: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            IPHONEOS_DEPLOYMENT_TARGET=14.0 \
            build
      - name: Create unsigned IPA
        script: |
          # Find the Runner.app in DerivedData
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "Runner.app" -type d | head -1)
          echo "Found app at: $APP_PATH"

          if [ -z "$APP_PATH" ]; then
            echo "Runner.app not found!"
            exit 1
          fi

          mkdir -p Payload
          cp -r "$APP_PATH" Payload/
          zip -r app-release-unsigned.ipa Payload
          rm -rf Payload
    artifacts:
      - app-release-unsigned.ipa

  android-workflow:
    name: Android Release Build
    max_build_duration: 30
    instance_type: linux_x2
    environment:
      flutter: stable
    scripts:
      - name: Create .env file
        script: |
          cp .env.production .env
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/**/app-release.apk
