workflows:
  ios-workflow:
    name: iOS Release Build (Unsigned)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      vars:
        PROD: "true"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Disable code signing in Xcode project
        script: |
          # Disable automatic code signing and set to manual
          cd ios
          /usr/libexec/PlistBuddy -c "Set :buildSettings:CODE_SIGN_IDENTITY ''" Runner.xcodeproj/project.pbxproj 2>/dev/null || true

          # Use sed to modify project.pbxproj
          sed -i '' 's/CODE_SIGN_IDENTITY = "iPhone Developer"/CODE_SIGN_IDENTITY = ""/g' Runner.xcodeproj/project.pbxproj
          sed -i '' 's/"CODE_SIGN_IDENTITY\[sdk=iphoneos\*\]" = "iPhone Developer"/"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = ""/g' Runner.xcodeproj/project.pbxproj
          sed -i '' 's/CODE_SIGN_STYLE = Automatic/CODE_SIGN_STYLE = Manual/g' Runner.xcodeproj/project.pbxproj

          # Add empty development team if not exists
          sed -i '' 's/DEVELOPMENT_TEAM = [^;]*;/DEVELOPMENT_TEAM = "";/g' Runner.xcodeproj/project.pbxproj
      - name: Build iOS (without codesigning)
        script: |
          flutter build ios --release --no-codesign --dart-define=PROD=true
      - name: Create unsigned IPA
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload
          zip -r ../../../app-release-unsigned.ipa Payload
    artifacts:
      - app-release-unsigned.ipa

  android-workflow:
    name: Android Release Build
    max_build_duration: 30
    instance_type: linux_x2
    environment:
      flutter: stable
      vars:
        PROD: "true"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build APK
        script: |
          flutter build apk --release --dart-define=PROD=true
    artifacts:
      - build/**/app-release.apk
