workflows:
  ios-workflow:
    name: iOS Release Build (Unsigned)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      vars:
        PROD: "true"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build iOS with xcodebuild (no signing)
        script: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            -allowProvisioningUpdates \
            FLUTTER_BUILD_MODE=release \
            DART_DEFINES="$(echo -n 'PROD=true' | base64)" \
            build
      - name: Create unsigned IPA
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload
          zip -r ../../../app-release-unsigned.ipa Payload
    artifacts:
      - app-release-unsigned.ipa

  android-workflow:
    name: Android Release Build
    max_build_duration: 30
    instance_type: linux_x2
    environment:
      flutter: stable
      vars:
        PROD: "true"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release --dart-define=PROD=true
    artifacts:
      - build/**/app-release.apk
